### ISSUE TITLE
Impossible de démarrer noethys

### ISSUE THREAD

**Issue by neoclust** [Noethys/Noethys#13]
$ python noethys/Noethys.py 
Traceback (most recent call last):
  File "noethys/Noethys.py", line 27, in <module>
    UTILS_Linux.AdaptationsDemarrage()
  File "/home/neoclust/Documents/Ecole/Noethys/noethys/Utils/UTILS_Linux.py", line 26, in AdaptationsDemarrage
    os.chdir(sys.path[1])
OSError: [Errno 20] Not a directory: '/usr/lib/python2.7/site-packages/sample-1.2.0-py2.7.egg'

**Comment by cg90160** [comment]
Salut,
C'est ma faute, j'ai utilisé un nouvel outil pour aider au debug, et selon comment les outils lancent le script, sys.path n'est pas initialisé de la même manière.
Tu peux recharger sur github le dernier UTILS_Linux.AdaptationsDemarrage, c'est corrigé.

**Comment by cg90160** [comment]
juste pour confirmer, avant de faire la mise à jour.
Est-ce que si tu le lances en faisant:
cd noethys
python Noethys.py
Ca fonctionne ?

**Comment by neoclust** [comment]
Effectivement ca fonctionne mieux maintenant.
Avant de lancer mon git pull j'ai tenté  d'aller dans le dossier noethys mais j'avais la meme erreur.

**Comment by cg90160** [comment]
Bno je ne sais pas exactement pourquoi mais selon l'outil que j'utilisais pour debugger le sys.path[0] me donnait une erreur.
En lisant la doc python:
As initialized upon program startup, the first item of this list, path[0], is the directory containing the script that was used to invoke the Python interpreter. If the script directory is not available (e.g. if the interpreter is invoked interactively or if the script is read from standard input), path[0] is the empty string, which directs Python to search modules in the current directory first. 

Du coup j'ai fait bourrin: si le 0 est vide je prends le 1 :-))
