### ISSUE TITLE
Noethys Full Web ?

### ISSUE THREAD

**Issue by samyscoub** [Noethys/Noethys#27]
Bonjour,

je recherche une solution de gestion de portail famille pour les mairies et je tombe sur votre projet.
Pouvez-vous me confirmer que la couple Noethys/Connecthys peut être installé sur un même serveur en ligne chez ovh par exemple et sans avoir besoin de bureau graphique ?

Pour l'instant en suivant votre documentation j'en arrive là en le lançant sur une debian 7 

```
~/Noethys/noethys# python Noethys.py
Traceback (most recent call last):
  File "Noethys.py", line 57, in <module>
    from Ctrl import CTRL_Portail_serveur
  File "/root/Noethys/noethys/Ctrl/CTRL_Portail_serveur.py", line 23, in <module>
    from Utils import UTILS_Portail_synchro
  File "/root/Noethys/noethys/Utils/UTILS_Portail_synchro.py", line 44, in <module>
    from Dlg.DLG_Portail_config import VALEURS_DEFAUT as VALEURS_DEFAUT_CONFIG
  File "/root/Noethys/noethys/Dlg/DLG_Portail_config.py", line 15, in <module>
    import wx.propgrid as wxpg
ImportError: No module named propgrid
```
Merci d'avance pour votre réponse.

Cordialement

**Comment by Noethys** [comment]
Bonjour,

Noethys n'est pas full web. Il ne peut être installé qu'en desktop (mais bon, vous pouvez quand l'installer sur un VPS windows OVH par exemple). Connecthys est une application web par contre. Mais Connecthys est totalement dépendant de Noethys.

L'erreur d'installation vient du fait que la version installée de wxPython est trop ancienne. Il faut installer une version plus récente : `apt-get install python-wxgtk3.0`

Ivan
