### ISSUE TITLE
Badgeage Voix Française 

### ISSUE THREAD

**Issue by hogsim** [Noethys/Noethys#33]
Bonjour, 
Lorsque l'on sélectionne Badgeage, configuration de la synthèse vocale et que l'on clic sur télécharger la voix française on arrive sur une page avec une erreur 404.

**Comment by cg90160** [comment]
Bonjour,

L'adresse du serveur de l'académie de Limoges a été modifiée.

Voici la bonne:
http://pedagogie.ac-limoges.fr/ia87/spip.php?article315

Je la corrigerai dans noethys pour la prochaine version publiée
