### ISSUE TITLE
Bug au démarrage

### ISSUE THREAD

**Issue by fpoulain** [Noethys/Noethys#55]
Bonjour,

Nous avons un bug au démarrage ; cf capture jointe.

![bug_noethys2](https://user-images.githubusercontent.com/32539071/52408337-00b77580-2ad3-11e9-91cc-bbec2e838bdb.png)

Une réinitialisation du logiciel évite le bug(en appuyant sur control au lancement), mais celui-ci réapparait souvent.

Sur ce poste, nous sommes obligés de réinitialiser noethys presque à chaque connexion.

**Comment by Noethys** [comment]
Bonjour,

Certains utilisateurs ont en effet rencontré ce bug. Pour y remédier, il suffit d'installer la version Beta 1.2.5.7. depuis le menu Téléchargements > Version Beta du site www.noethys.com.

Ivan
