### ISSUE TITLE
Impossible d'importer les dates des vacances depuis internet

### ISSUE THREAD

**Issue by tech62** [Noethys/Noethys#67]
Bonjour,

J'essaie de mettre à jour les dates de vacances depuis internet, mais la fenêtre en dessous de la sélection de la zone reste vide.

Noethys est à jour.

Merci pour votre aide !

**Comment by Noethys** [comment]
Bonjour,

Le site de l'éducation nationale a déplacé la source. La version 1.2.9.1. corrige ce problème. 

Ivan
