### ISSUE TITLE
Souci installation Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Mireille64** [Noethys/Noethys#81]
Bonjour,
J'essaie d'installer Noethys sous Ubuntu 22.04 LTS, mais je n'y arrive pas.
Quelqu'un pourrait-il m'aider à éclairer le souci s'il vous plaît ?

**Comment by JurassicPork** [comment]
Hello,
Olivier Bitsch a pas mal travaillé pour faire fonctionner Noethys avec du python 3.10 en éliminant le genre de problème que tu as. J'ai "forké" son dépôt github et fait quelques modifs. Ma version se trouve [ici](https://github.com/JurassicPork/Noethys)
Le **Readme** est modifié pour l'adapter à un Ubuntu 22.04 . J'ai enlevé aussi pour l'instant l'installation du paquet  python mysqlclient qui me fait une erreur en installation.
En suivant la procédure indiquée dans le **Readme**, NoEthys se lance sous Ubuntu 22.04 avec un python 3.10. 
Ami calmant, J.P

**Comment by Mireille64** [comment]
Super, merci.
Je ne sais plus bien quel était le souci ; je sais que j'avais déjà eu du mal à trouver comment adapter le code pour le passer du Ubuntu 20.04 à Ubuntu 22.04 (un truc hyper simple une fois que tu as compris, mais que, comme souvent, j'ai mis beaucoup de temps à décrypter...)
Ensuite un souci avec la version de python à récupérer, puis un abandon parce que je ne savais plus où j'en étais.

**Comment by Mireille64** [comment]
Bon, je viens de tenter l'installation... et tout d'un coup, tout semble effectivement fonctionner direct sans souci...
Merci !

**Comment by Mireille64** [comment]
Hum... Encore une question hyper basique : pour lancer Noethys, il faut que je fasse appel à quelle commande ?
Il me semble me souvenir qu'il faut que j'y fasse appel via python, mais je ne sais plus précisément avec quelle commande.

**Comment by Fred-gith** [comment]
de mémoire :
#python noethys.py

**Comment by Mireille64** [comment]
Merci.
Bon, si certains passent par ici et font autant de mauvaises manip' que moi, je précise : 
* Ouvrir un terminal
* Y écrire : python3 Noethys/noethys/Noethys.py
